tag: zh-classification
task: financeiq
dataset_path: TheFinAI/multifinben-zh-FinanceIQ
dataset_name: default
test_split: test
output_type: multiple_choice
doc_to_text: '{{query}}'
doc_to_target: gold
doc_to_choice: choices
fewshot_split: valid
target_delimiter: ""
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
