tag: zh-classification_gen
task: financeiq_gen
dataset_path: TheFinAI/multifinben-zh-FinanceIQ
dataset_name: default
test_split: test
output_type: generate_until
doc_to_text: '{{query}}'
doc_to_target: '{{answer}}'
fewshot_split: valid
target_delimiter: ""
generation_kwargs:
  until:
    - "."
    - ","
  do_sample: false
  temperature: 0.0
  max_gen_toks: 30
filter_list:
  - name: "score-first"
    filter:
      - function: "regex"
        regex_pattern: "(Α|Β|C|D)"
      - function: "take_first"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
