dataset_name: default
dataset_path: TheFinAI/flare-es-efp
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
output_type: generate_until
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "."
    - ","
  do_sample: false
  temperature: 0.0
  max_gen_toks: 30
filter_list:
  - name: "score-first"
    filter:
      - function: "regex"
        regex_pattern: "(Α|Β|C)"
      - function: "take_first"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
task: ESEFP_gen
tag: es_gen
test_split: test
