dataset_name: default
dataset_path: TheFinAI/flare-es-financees
doc_to_target: gold
doc_to_text: '{{query}}'
output_type: multiple_choice
doc_to_choice: choices
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
task: ESFINANCEES
tag: es
test_split: test
