dataset_name: default
dataset_path: TheFinAI/flare-es-fns
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  do_sample: false
  temperature: 0.0
  max_gen_toks: 512
metric_list:
  - metric: !function es_utils.rouge1
    aggregation: !function es_utils.rouge1_agg
    higher_is_better: true
metadata:
  version: '1.0'
task: ESFNS
tag: es
test_split: test
