dataset_name: default
dataset_path: TheFinAI/DOLFIN_en_es_test
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  do_sample: false
  temperature: 0.0
  max_gen_toks: 1024
metric_list:
  - metric: !function dolfin_utils.comet
    aggregation: !function dolfin_utils.comet_agg
    higher_is_better: true
metadata:
  version: '1.0'
task: DoLFin
tag: dolfin
test_split: test
training_split: train