dataset_name: default
dataset_path: TheFinAI/flare-dm-simplong
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "@@"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 1024
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
task: simplelong
tag: fin
test_split: test
training_split: test
