tag: zh-classification
task: reg-relation-classification
dataset_path: TheFinAI/multifinben-zh-regrelation
dataset_name: default
test_split: test
output_type: multiple_choice
doc_to_text: '{{query}}'
doc_to_target: gold
doc_to_choice: choices
#fewshot_config:
target_delimiter: ""
#  sampler: first_n
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: acc_norm
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
