tag: zh-classification_gen
task: reg-legal-name-classification_gen
dataset_path: TheFinAI/multifinben-zh-legalname
dataset_name: default
test_split: test
output_type: generate_until
doc_to_text: '{{query}}'
doc_to_target: '{{answer}}'
fewshot_split: train
target_delimiter: ""
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "."
    - ","
  do_sample: false
  temperature: 0.0
  max_gen_toks: 30
filter_list:
  - name: "score-first"
    filter:
      - function: "regex"
        regex_pattern: "(财经法规|财政法规|个人所得税|金融综合|劳动就业|上市公司|社会保障|行业管理|增值税|征收管理|资产评估法规|资源税|综合管理|综合税收政策)"
      - function: "take_first"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
